### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber" : "1000000002",
  "amount": 2000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber" : "1000000002",
  "amount": 2000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "2b4e092bcab5474dac9cc4988f467f9f",
  "accountNumber" : "1000000002",
  "amount": 2000
}

### query transaction
GET http://localhost:8080/transaction/2b4e092bcab5474dac9cc4988f467f9f